import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Layout from "@/components/layout/layout";
import Providers from "@/lib/ReactQueryProviders";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.ttf",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <main>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </main>
      </body>
    </html>
  );
}
